### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by SanderMertens** [SanderMertens/bake#1]
Enable bake projects to be built on Windows.

For the port, the following items need to happen:
- A port of the bake code. Bake is already using a operating system independent API which is located in the "util" directory. This code includes pthread (threading), dl (shared objects), exec* functions (spawning processes) and file system operations.

- Adapt package management to Windows. In macOS / Linux, bake is stored in $HOME/bake. On Windows, it would make sense to also store packages under the user's directory. References to $HOME and ~ will have to be ported to point to the Windows equivalent.

- Port environment management. Bake manages environment variables, and automatically exports variables when building. It automatically finds a configuration file in the current path which contains the variables, and exports them within the scope of the process. The Windows command line doesn't have the concept of "sourcing", so exporting the bake environment to a shell will have to work differently.

- Make bake executable available across the system. When bake is installed on macOS or Linux, a shell script is installed to /usr/local/bin that invokes a bake executable stored in the user $HOME directory. This allows different users to have different versions of bake. For Windows a similar system needs to be invented.

- Create a bake driver that either invokes the Microsoft Visual Studio compiler. The interface should be largely the same as the macOS/Linux C driver, but obviously compiler commands will be different.

To ensure that this functionality works and keeps working, this issues should not be closed until there is a Windows CI build that validates whether the aforementioned is working,.

**Comment by simon-p-r** [comment]
Hi

Are you willing to accept PRs for this?

Thanks
Simon

**Comment by SanderMertens** [comment]
Hi @simon-p-r, sorry I missed your comment somehow! Because this is such a complex capability to implement, I wanted to oversee the initial bulk of the work. This is now almost done, which means Windows support is around the corner!

However, I do expect that there will be many improvements and new features that will need to be added. For this, I'd definitely welcome PRs!
