### ISSUE TITLE
First time `bake` user experience

### ISSUE THREAD

**Issue by penberg** [SanderMertens/bake#11]
As a `bake` newbie with plenty of `cargo` experience (similar tool in Rust world), I created my first project:

```console
$ bake init hello
Created new package with id 'hello'
```

I then proceeded to build the project with `bake`:

```console
$ cd hello
$ bake
build package 'hello' in '.'
```

OK, so it built something, but _what_ and _where_? Running `find` reveals that it built a shared library:

```console
$ find .
...
./bin/x64-linux-debug/libhello.so
```

I suppose I need to configure project type somehow. The output of `bake init -h` shows that the main `bake` executable has a `--type` command line option:

```console
$ bake init --help
Usage: bake [options] <command> <path>

Options:
  ..
  --type <project type>        Manually specify a project type (default = "package")
```

I assume that can be passed to `bake init` too, but what value to pass if I want an regular executable?

The tool does not seem to provide any information:

```console
$ bake init --type list hello
error 'list' is not a valid project kind
$ bake init --type help hello
error 'help' is not a valid project kind
```

So with a little bit of help from `git grep`, I managed to find the right type:

```console
$ bake init --type application hello
Created new application with id 'hello'
```

I can also build it:

```console
cd hello
bake
$ which bin/x64-linux-debug/hello
./bin/x64-linux-debug/hello
```

It's bit annoying to have to type `bake` and that long executable path but perhaps `bake` can do it for us:

```console
$ bake run
error path 'run' not found
```

Unfortunately not.

For reference, here's what the session would have looked like with `cargo`:

```console
$ cargo init hello
     Created binary (application) project
$ cd hello
$ cargo run
   Compiling hello v0.1.0 (/home/penberg/tmp/hello)
    Finished dev [unoptimized + debuginfo] target(s) in 0.84s
     Running `target/debug/hello`
Hello, world!
```

Oh, but what if I had actually wanted to build a library?

```
penberg@nero tmp]$ cargo init --help
cargo-init
Create a new cargo package in an existing directory

USAGE:
    cargo init [OPTIONS] [--] [path]

OPTIONS:
        ...
        --bin               Use a binary (application) template [default]
        --lib               Use a library template

ARGS:
    <path>     [default: .]
```

Looks like I need to pass the `--lib` argument to `cargo init`.

**Comment by SanderMertens** [comment]
Thanks, that is really useful feedback! I'll update the command-line help accordingly. `bake run` is actually something on my TODO shortlist. In its previous incarnation (before the fork) that functionality was handled by another project.

**Comment by SanderMertens** [comment]
I've added a `bake run` command, and changed the default project type to application. So now you can do:

```
bake init foobar
bake run foobar
```

Furthermore, since bake can find projects regardless of where you run it from, you can run `bake run foobar` from any location, and it will run the foobar project.

I've also added an interactive mode, which automatically rebuilds and restarts the project when you change a file in the project directory. To do this, add `--interactive` to the command, like this:

```
bake run foobar --interactive
```

If you want to pass arguments to the application, you can do that with `-a` or `--args` (also works in non-interactive mode):

```
bake run foobar --interactive -a arg0 arg1
```

If you want to create a new package (library) project, you can now simply do:
```
bake init my_library --package
```

I've also updated the command line help with more helpful descriptions and examples.

**Comment by SanderMertens** [comment]
I changed the setup to no longer abort after copying the script to `/usr/local` fails. If this happens, the setup will log a warning that notifies the user to first do `export $(~/bake/bake env)`

**Comment by SanderMertens** [comment]
I think all the issues you mentioned have been addressed, so I'll close the issue. Thanks again for the feedback!
