### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [SanderMertens/bake#12]
Would you like to add more error handling for return values from functions like the following?
- [fopen](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "Open a stream") ⇒ [setup_project](https://github.com/SanderMertens/bake/blob/42841b743ab839c80b3d181e19aba2ef5fff3801/drivers/lang/c/src/c.c#L500)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [bake_version](https://github.com/SanderMertens/bake/blob/42841b743ab839c80b3d181e19aba2ef5fff3801/src/main.c#L103)

**Comment by SanderMertens** [comment]
Nice catch! I've added error checking for the `fopen` calls. What do you suggest bake should do when `printf` fails?

**Comment by elfring** [comment]
* How do you think about to [choose a corresponding program error code](https://en.wikipedia.org/wiki/Exit_status#C_language "Selection of an exit status")?
* Would you like to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by SanderMertens** [comment]
@elfring 
> How do you think about to choose a corresponding program error code?
If you suggest to exit the program with an error code when printf fails, I'd rather not. Being able to print to a terminal is not crucial to bake's core functionality, and it could complicate running it in some environments.

> Would you like to improve static source code analysis also for this software?
Yes, anything that improves the quality of the code will be considered!

I will close this issue for now. If you'd like to discuss static analysis, feel free to open a new issue.

**Comment by elfring** [comment]
Advanced source code analysis will point more remaining update candidates out, won't it?
