### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [SanderMertens/bake#13]
[An extra null pointer check is not needed](https://github.com/SanderMertens/bake/blob/f733033d630b27a2e19e6bc0627f6e0b580c6227/util/src/ll.c#L52 "Do I need to check for null before ut_ll_free(p)?") in [the function “link_dynamic_binary”](https://github.com/SanderMertens/bake/blob/c0a21f3f79aca8217bc1bd051537ccb5899d1f44/drivers/lang/c/src/main.c#L456 "Update candidate: link_dynamic_binary()").

**Comment by SanderMertens** [comment]
This check is not unnecessary,

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/SanderMertens/bake/commit/afd64ec9c4707c1a690c02ae2e555f7af811bacd "Deletion of a redundant pointer check").
