### ISSUE TITLE
bake clone doesnt work

### ISSUE THREAD

**Issue by hunar1997** [SanderMertens/bake#19]
It says cloning into etc... then after a second it says segmentation fault core dumped   
is it just me? i tried multiple repositories

**Comment by SanderMertens** [comment]
I'm sorry to hear that! I just tried cloning a bake repository, and it seems to work for me. Can you show me the command you are trying out?

**Comment by hunar1997** [comment]
OOOOOO I'm sorry i was doing something wrong, it was working i just was trying a wrong repository
