### ISSUE TITLE
Change project path

### ISSUE THREAD

**Issue by yuvaldolev** [SanderMertens/bake#25]
Hi,
I'm currently using bake for one of my c++ projects and I really love it.
I want to move the location of the project to another directory on my computer.
Can you change the path to the project without uninstalling & reinstalling the project (using bake uninstall & bake install)?

Thanks,
Yuval Dolev

**Comment by SanderMertens** [comment]
Short answer is yes, you can do this. You don't need to install/uninstall the project after moving the directory. Bake copies binaries to the _bake environment_ (typically in `$HOME/bake`) so even after moving a project, you can still run things that depend on your project.

However, bake creates _softlinks_ to header files in the bake environment, and when you move your project those links will be broken. Thus when you try to rebuild something that depends on your moved project, you'll get an error saying it can't find the header file.

To solve this, you don't need to uninstall/install. Simply run `bake` again after you've moved the project, and the links will be updated.

**Comment by yuvaldolev** [comment]
Great! Thanks
