### ISSUE TITLE
Name collision 

### ISSUE THREAD

**Issue by dlachausse** [SanderMertens/bake#8]
Just so you're aware there is already a VERY similar project with the same name already in existence. You might want to rename this before it gets much traction. 

https://github.com/vslavik/bakefile

**Comment by SanderMertens** [comment]
Thanks for making me aware of this! For now, I think the similarity in names is ok. While bake and bakefile share similar goals and solve similar problems, the way in which they do it is quite different (bakefile is a makefile generator, whereas bake is its own build system).

I think we can peacefully coexist for now. If bakefile (or another project that shares the same name) becomes big (like CMake big) I will definitely consider renaming the project.
